name: Python ofek

on: [push, pull_request]

jobs:
  test-mysql:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7]
    env:
      PYTHONPATH: ${{ github.workspace }}
      SUPERSET_CONFIG: tests.superset_test_config
      REDIS_PORT: 16379
      SUPERSET__SQLALCHEMY_DATABASE_URI: |
        mysql+mysqldb://superset:superset@127.0.0.1:13306/superset?charset=utf8mb4&binary_prefix=true
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 13306:3306
      redis:
        image: redis:5-alpine
        options: --entrypoint redis-server
        ports:
          - 16379:6379
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2.1.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      uses: apache-superset/cached-dependencies@b90713b
      with:
        run: |
          apt-get-install
          pip-upgrade
          pip install -r requirements/testing.txt
          setup-mysql
    - name: Python unit tests (MySQL)
      run: |
        ./scripts/python_tests.sh dashboards/api_tests.py
